batch_size: 4
data_path: /adialab/usr/khaled/SAMTOK_DIR/AVMUR/baselines/artifacts/unime/data
dataset_name: BRATS2023
split_type: Normal
train_ratio: null
crop_size: 96
log_root: /adialab/usr/khaled/SAMTOK_DIR/AVMUR/baselines/artifacts/unime/benchmark_runs/unime_20260923_01/pretrain
wandb_mode: disabled
wandb_project: UniME
wandb_entity: null
wandb_run_name: UniME-BRATS2023-Paper-Pretrain
wandb_group: null
base_lr: 0.0003
warmup_lr: 1.0e-05
min_lr: 1.0e-06
warmup_ratio: 0.05
weight_decay: 0.0001
num_epochs: 600
iter_per_epoch: 250
log_freq: 5
num_workers: 8
persistent_workers: true
prefetch_factor: 2
profile_data_pipeline: false
profile_warmup_steps: 20
gpu_ids: '0'
seed: 40
amp: true
bfloat16: false
compile: true
flash_attn: false
use_ema: true
ema_decay: 0.999
ema_validate_interval: 1
ema_validate_start_epoch: 500
mask_ratio: 0.75
modality_mask_prob: 0.5
num_mask_modalities: 3
original_shape:
- 160
- 180
- 210
deep_supervised: false
regulization_rate: 0.005
model_name: UniEncoder
